### ISSUE TITLE
Add a loading state on initial page load, while waiting for api call to return

### ISSUE THREAD

**Issue by maxleaver** [tbytheway/ticketing-system#1]
Sometimes, if the API call takes a second to complete, an empty version of the table is displayed. Let's replace it with a loading state that disappears once the API has returned data.

**Comment by tbytheway** [comment]
I found an NPM module, a promise tracker.  When I wrap my axios.get in trackpromise() I get this error.  I can't see why my componentDidMount is ticked at that.

ERROR in ./src/components/dashboard.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: D:/Repository/Capstone/ticketing-system/src/components/dashboard.js: Unexpected token, expected { (88:4)

  86 |       })
  87 | 
> 88 |     componentDidMount() {
     |     ^
  89 |         this.getTickets()
  90 |     }
  91 |

**Comment by maxleaver** [comment]
Before you introduce a package to your application, you already have a mechanism to know when your promise completes. In your `getTickets` method, when your API call completes, the `.then` or `.catch` methods are fired. What if you added a `loading` property to your component state that was initially true, but gets set to false when you either receive data or there is an error?

```
getTickets = () => {
  axios.get("https://tdb-ticket-api.herokuapp.com/tickets")
    .then(res => {
      this.setState({
          tickets: res.data
        })
      })
      .catch(function (error) {
          console.log(error);
        });
      }
```

**Comment by tbytheway** [comment]
Added a Loading...Patience Danielson.
