### ISSUE TITLE
Make ticket titles look like links

### ISSUE THREAD

**Issue by maxleaver** [tbytheway/ticketing-system#2]
It's not clear on the dashboard that you can click on a ticket link. Let's make the title look like a link, including changing the mouse cursor to a pointer when you hover over it.

**Comment by tbytheway** [comment]
I made the font-weight bold on hover.  I'm really not a style guy.  I like it when things look cool, but I'm not the one coming up with it.

**Comment by maxleaver** [comment]
What's the best way to help you out in the styling area? Would it help to have a mockup that you could style against?

**Comment by tbytheway** [comment]
That's not a bad idea.  I find implementing stiles pretty easy. It's having
the eye for what looks good. That's where I lack.
