### ISSUE TITLE
Convert "Thanks" component to a stateless component

### ISSUE THREAD

**Issue by maxleaver** [tbytheway/ticketing-system#9]
React has two types of components:

- **Stateful** - Has an internal state that can change based on logic or parameters passed from a parent.
- **Stateless** - Components that are simply presentational and contain no logic.

Stateless components include some performance benefits. They use a slightly different format from what you may be used to. There is a 2nd issue to convert RenderTickets to a stateless component. I'll submit a pull request for that item so you can see the simplified code format and use it for reference here.

**Comment by tbytheway** [comment]
Stateless.
